app:
  version: 3.0.0

metrics:
  serviceMonitor:
    enabled: true

mysql:
  master:
    persistence:
      size: 1Gi
  image:
    tag: 5.7.27
  db:
    name: "myapp"
    user: "admin"
    password: "112233"
  replication:
    enabled: false