apiVersion: batch/v1
kind: Job
metadata:
  name: task4-migrate
spec:
  completions: 1
  template:
    metadata:
      name: task4-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          envFrom:
              - configMapRef:
                  name: task4-config
          image: gorasu/task4:v1
          command:
            - sh
            - "-c"
            - |
              cd ../ && php bin/console doctrine:migrations:migrate -n --env=prod