apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
spec:
  selector:
    app: task4-label-dep
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort
